name: Hello Workflow

on: 
  push:     # triggers when code is pushed to repo
    branches:
      - main

jobs:
  say-hello:
    runs-on: ubuntu-latest   # GitHub provides a Linux runner VM
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3   # pulls your repo code into the runner

      - name: Say Hello
        run: echo "Hello GitHub Actions!"